name: github-action-learning
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - main

jobs:
  Python-SetUp:
    runs-on: 'self-hosted'  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        run: |
          sudo yum update -y
          sudo yum install python3 -y

      - name: Check Python version
        run: python3 --version

  Docker-SetUp:
    runs-on: 'self-hosted'  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          sudo yum update -y
          sudo yum install docker -y
          sudo service docker start
          sudo usermod -a -G docker $USER  # Add the current user to the docker group
          newgrp docker  # Activate the changes to the group membership
          

      - name: Check Docker version
        run: docker --version
