name: github-action-learning
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - main

jobs:
  Python-SetUp:
    runs-on: 'self-hosted'  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        run: |
          sudo yum update -y
          sudo yum install python3 -y

      - name: Check Python version
        run: python3 --version

  Docker-SetUp:
    runs-on: 'self-hosted'  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          sudo yum update -y
          sudo yum install docker -y
          sudo service docker start
          sudo usermod -a -G docker $USER  # Add the current user to the docker group
          newgrp docker  # Activate the changes to the group
          
      - name: Check Docker version
        run: docker --version

  MySQL-SetUp:
    runs-on: 'self-hosted'  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up MySQL Container
        run: |
          # Pull the MySQL Docker image
          docker pull mysql:latest

          # Run MySQL container
          docker run --name mysql-container -e MYSQL_ROOT_PASSWORD=your_password -d -p 3306:3306 mysql:latest

          # Wait for MySQL to start (adjust the sleep duration as needed)
          sleep 30

      - name: Check MySQL Database
        run: |
          # Connect to MySQL and execute a query
          docker exec -it mysql-container mysql -uroot -p'your_password' -e "SHOW DATABASES;"
