name: github-action-learning
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - main

jobs:
  check-Docker-Python-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Check Docker version
        run: docker --version

  python-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python and check version
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Specify your Python version here

      - name: Check Python version
        run: python --version
