name: github-action-learning
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - main

jobs:
  Python-SetUp:
    runs-on: 'self-hosted'  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        run: |
          sudo yum update -y
          sudo yum install python3 -y

      - name: Check Python version
        run: python3 --version

  SQL-Server-SetUp:
    runs-on: 'self-hosted'  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SQL Server
        run: |
          # Install SQL Server (example commands for CentOS)
          sudo curl -o /etc/yum.repos.d/msprod.repo https://packages.microsoft.com/config/rhel/8/prod.repo
          sudo yum install -y mssql-tools unixODBC-devel
          
          # Wait for SQL Server to start
          sleep 60

          # Connect to SQL Server and execute a query
          /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P Your_Password123 -Q "SELECT name FROM sys.databases;"
