name: github-action-learning
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - main

jobs:
  Python-SetUp:
    runs-on: 'self-hosted'  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python and check version
        uses: actions/setup-python@v2
        with:
          python-version: 'latest' # Specify your Python version here

      - name: Check Python version
        run: python --version

  Docker-SetUp:
    runs-on: 'self-hosted'  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Check Docker version
        run: docker --version
